# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.EmailField(default='s@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
