# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prof', '0002_worker_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='age',
            new_name='cell_number',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='id',
        ),
        migrations.AddField(
            model_name='worker',
            name='address',
            field=models.CharField(default='Calle', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='city',
            field=models.CharField(default='Bogota', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='id_worker',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='profession',
            field=models.CharField(default='Ingeniero', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='sex',
            field=models.CharField(choices=[('W', 'Women'), ('M', 'Men')], default='W', max_length=10),
        ),
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
