# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prof', '0003_auto_20160122_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='id_worker',
        ),
        migrations.AddField(
            model_name='worker',
            name='id',
            field=models.AutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
