# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prof', '0004_auto_20160122_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='sex',
        ),
    ]
