# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prof', '0006_remove_worker_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='cell_number',
            new_name='cellphone',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='worker',
            name='profession',
            field=models.CharField(default='Hola', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
