# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prof', '0007_auto_20160122_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
