# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prof', '0009_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='cnt',
            field=models.IntegerField(default=0),
        ),
    ]
