# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prof', '0010_auto_20160122_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='counter',
        ),
    ]
