# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prof', '0012_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='name',
            field=models.CharField(default='general', max_length=10),
            preserve_default=False,
        ),
    ]
